### ISSUE TITLE
feature: soluce command in the CLI

### ISSUE THREAD

**Issue by tdelabro** [onlydustxyz/starklings#100]
using this command (on a specific exercise or while in `watch mode`) will patch the exercise file with it's solution
steps:
- `git restore -s origin/main <path to exercise file>` (in order to get rid of any user modification and avoid conflicts)
- `patch <path to exercise file> <path to corresponding patch file>`

**Comment by tdelabro** [comment]
To discuss:
This put the solution directly in the exercise, is this the best way to display it to the end user ? Maybe creating a new `soluce` file instead could be good ? Or just displaying it in the terminal ?

**Comment by Bernardstanislas** [comment]
@tdelabro be aware that `soluce` sounds very French, you might to go with `solution` or `solve`
