### ISSUE TITLE
Solution not displaying and showing error

### ISSUE THREAD

**Issue by 0xAurelou** [onlydustxyz/starklings#149]
Hello,
 I can't display the solution for an exercise.
How to reproduce this issue:
get to the root of the repo,
Use the command : starklings -s exercises/recursions/recursion01.cairo

![image](https://user-images.githubusercontent.com/63618058/170001769-f01f0153-ae7f-4884-b8ee-c93f74bc543c.png)

**Comment by tekkac** [comment]
Hello @0xAurelou,
  Thanks for the feedback!
  This error might have been solved in a newer version of Starklings:
  - make sure you pull the latest changes from the repository (`git pull`)
  - install the latest version using the command `bash install.sh` in the root directory

**Comment by Bernardstanislas** [comment]
For the record I created this issue to make it impossible to happen in the futureL: https://github.com/onlydustxyz/starklings/issues/15
