### ISSUE TITLE
Patches not processed correctly

### ISSUE THREAD

**Issue by tekkac** [onlydustxyz/starklings#165]
## Description
  When displaying a solution with the command `python starklings.py -s path/to/exercise.cairo`, mid-file changes are applied one line above the actual changes which can break solutions.
This looks like an _off-by-one_ issue in the patch library used in `src/solutions.py`

## Acceptance criteria
  - Patching an exercise file should give the same output as `patch exercise.cairo solution.cairo -o -`

**Comment by Bernardstanislas** [comment]
@tdelabro I take it since I include it in the work of generating the solutions upon binary build using hooks
