### ISSUE TITLE
Deploy exercise verifier as a Flask API

### ISSUE THREAD

**Issue by Bernardstanislas** [onlydustxyz/starklings#206]
The idea of this issue is to prepare the work of creating a web version of Starklings.

A first step for that would be to have a simple Flask backend that will expose one route `POST /exercise/check?path={exercise_path}` that returns the errors of the exercise file given as the request body.

This would be used by a frontend exposing a code editor to the user, and calling this API to get a correction on the exercise.

**Comment by sxxnx** [comment]
**🗒️ Information about the data needed for front end**  :
*(types are for ref. it can be easily handled with JS if needed*) *
- user id *(number or strg)*
- user address *(number)*
- user progression ⚠️ **by exercice type** (*Array of Object*)
``` json
[{
  "userProgression": {
    "syntax": {
      "syntax0": "success",
       "syntax1": "not-started"
     }
  }
}]
````
- also a list of all exercices (type + all the exercices included in the type) is necessary
