### ISSUE TITLE
Beginner exercises ideas

### ISSUE THREAD

**Issue by tdelabro** [onlydustxyz/starklings#68]
Right now we have 5 beginners exercises, that cover:
- storage
- externals and views
- structures
- arrays and recursion
- basic revocated references occurences

I believe we can add a few more exercises to cover more of cairo features  and edge cases.
Feel free to submit ideas about what you would like to see this tutorial cover in the future !

**Comment by Bernardstanislas** [comment]
@tdelabro I think we now have covered the listed subjects, wdyt about closing this issue?

**Comment by Bernardstanislas** [comment]
@tekkac I suggest we close this issue since it's quite general, maybe create more specific ones with what you are actually working on?

**Comment by tekkac** [comment]
Agreed, specific issues are the way to go.
