### ISSUE TITLE
starklings --watch does not work

### ISSUE THREAD

**Issue by Alex-Derhacobian** [onlydustxyz/starklings#93]
I've followed all the installation steps, but when I run starklings, the only command-line flags that are available are --help and --version. I'm running this all on a 2020 MacBook Pro (Intel). I have done the following
1. Install protostar
2. git clone https://github.com/onlydustxyz/starklings.git
3. cd starklings
4. curl -L https://raw.githubusercontent.com/onlydustxyz/starklings/master/install.sh | bash
Am I doing something wrong here?

**Comment by Bernardstanislas** [comment]
You are not doing anything wrong sir, we just need to publish the latest version you get installing `starklings`.
We were waiting for the first exercises refactoring to make it work with the watch mode, we'll publish it today and I'll let you know when it's available.

**Comment by Alex-Derhacobian** [comment]
Awesome, thanks! Sorry for the misunderstanding

**Comment by Bernardstanislas** [comment]
Thank you for pointing this out! We are still in the early days of the project so we need to put in place a lot of good practices including a clear release planing.

**Comment by Bernardstanislas** [comment]
@Alex-Derhacobian [v0.1.0](https://github.com/onlydustxyz/starklings/releases/tag/v0.1.0) is out, you can try it today :)
